on:
  push:
    paths:
      - "evm-chain/**"
      - ".github/workflows/evm-chain-ci.yml"
  pull_request:
    paths:
      - "evm-chain/**"
      - ".github/workflows/evm-chain-ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: evm-chain

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm run complite
      - name: Install dependencies
        run: npm ci
      - name: Complite evn-chain
      - name: Run tests
        run: npm test --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Type check
        run: npm run type-check --if-present

