name: Smart Contracts Linux Check

on:
  push:
    paths:
      - "smart-contracts/**"
  pull_request:

jobs:
  contracts-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: smart-contracts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: smart-contracts/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Compile smart contracts
        run: npx hardhat compile
